In [ ]:
import numpy as np

In [ ]:
import numpy as np

print(np.__version__)

2.0.2


In [ ]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])

# 2D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\n3D Array:")
print(arr3)

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print("Shape of 1D Array:", arr1.shape)
print("Shape of 2D Array:", arr2.shape)
print("Shape of 3D Array:", arr3.shape)

Shape of 1D Array: (5,)
Shape of 2D Array: (2, 3)
Shape of 3D Array: (2, 2, 2)


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

vector = np.array([10,20,30])

result = matrix + vector

print("Matrix:")
print(matrix)

print("\nVector:")
print(vector)

print("\nBroadcasting Result:")
print(result)

Matrix:
[[1 2 3]
 [4 5 6]]

Vector:
[10 20 30]

Broadcasting Result:
[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("Addition:")
print(a + b)

print("Subtraction:")
print(a - b)

print("Multiplication:")
print(a * b)

print("Division:")
print(a / b)

print("Square:")
print(a ** 2)

Addition:
[ 7  9 11 13 15]
Subtraction:
[-5 -5 -5 -5 -5]
Multiplication:
[ 6 14 24 36 50]
Division:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Square:
[ 1  4  9 16 25]


In [ ]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

C = A @ B

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

print("\nMatrix Multiplication")
print(C)

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Matrix Multiplication
[[19 22]
 [43 50]]


In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [ ]:
numeric_data = df.select_dtypes(include='number')

data = numeric_data.to_numpy()

print(data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
mean = np.mean(data, axis=0)

print("Mean")
print(mean)

Mean
[5.84333333 3.05733333 3.758      1.19933333]


In [ ]:
std = np.std(data, axis=0)

print("Standard Deviation")
print(std)

Standard Deviation
[0.82530129 0.43441097 1.75940407 0.75969263]


In [ ]:
correlation = np.corrcoef(data, rowvar=False)

print("Correlation Matrix")
print(correlation)

Correlation Matrix
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [ ]:
columns = numeric_data.columns

print("Mean Values")
for c, m in zip(columns, mean):
    print(f"{c}: {m:.2f}")

print("\nStandard Deviation")
for c, s in zip(columns, std):
    print(f"{c}: {s:.2f}")

print("\nCorrelation Matrix")
print(correlation)

Mean Values
sepal_length: 5.84
sepal_width: 3.06
petal_length: 3.76
petal_width: 1.20

Standard Deviation
sepal_length: 0.83
sepal_width: 0.43
petal_length: 1.76
petal_width: 0.76

Correlation Matrix
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
